[package]
name = "rrg-proto"
version = "0.1.0"
authors = ["≈Åukasz Hanuszczak <hanuszczak@google.com>"]
edition = "2018"

[dependencies]
prost = { version = "0.6.1" }
prost-types = { version = "0.6.1" }

[build-dependencies]
prost-build = { version = "0.6.1" }
